version: "4.42"

services:
  postgres2:
    container_name: postgres2
    image: postgres:latest
    networks:
      - net
    command:
      ["postgres", "-c", "max_connections=1000", "-c", "listen_addresses=*"]
    restart: always
    ports:
      - 5432:5432

    environment:
      - POSTGRES_USER=User
      - POSTGRES_PASSWORD=Password
      - POSTGRES_DB=database

    volumes:
      - postgres_data2:/var/lib/postgresql/data
    expose:
      - 5432

volumes:
  postgres_data2:

networks:
  net:
    driver: bridge
